*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /YKY/EXP_COMPIDV................................*
FORM GET_DATA_/YKY/EXP_COMPIDV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /YKY/EXP_COMPID WHERE
(VIM_WHERETAB) .
    CLEAR /YKY/EXP_COMPIDV .
/YKY/EXP_COMPIDV-MANDT =
/YKY/EXP_COMPID-MANDT .
/YKY/EXP_COMPIDV-EXPENSE_SYSTEM =
/YKY/EXP_COMPID-EXPENSE_SYSTEM .
/YKY/EXP_COMPIDV-SYSID =
/YKY/EXP_COMPID-SYSID .
/YKY/EXP_COMPIDV-CLIENT =
/YKY/EXP_COMPID-CLIENT .
/YKY/EXP_COMPIDV-COMPANY_ID =
/YKY/EXP_COMPID-COMPANY_ID .
/YKY/EXP_COMPIDV-USER_ID =
/YKY/EXP_COMPID-USER_ID .
<VIM_TOTAL_STRUC> = /YKY/EXP_COMPIDV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/YKY/EXP_COMPIDV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /YKY/EXP_COMPIDV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/YKY/EXP_COMPIDV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /YKY/EXP_COMPID WHERE
  EXPENSE_SYSTEM = /YKY/EXP_COMPIDV-EXPENSE_SYSTEM AND
  SYSID = /YKY/EXP_COMPIDV-SYSID AND
  CLIENT = /YKY/EXP_COMPIDV-CLIENT AND
  COMPANY_ID = /YKY/EXP_COMPIDV-COMPANY_ID .
    IF SY-SUBRC = 0.
    DELETE /YKY/EXP_COMPID .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /YKY/EXP_COMPID WHERE
  EXPENSE_SYSTEM = /YKY/EXP_COMPIDV-EXPENSE_SYSTEM AND
  SYSID = /YKY/EXP_COMPIDV-SYSID AND
  CLIENT = /YKY/EXP_COMPIDV-CLIENT AND
  COMPANY_ID = /YKY/EXP_COMPIDV-COMPANY_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /YKY/EXP_COMPID.
    ENDIF.
/YKY/EXP_COMPID-MANDT =
/YKY/EXP_COMPIDV-MANDT .
/YKY/EXP_COMPID-EXPENSE_SYSTEM =
/YKY/EXP_COMPIDV-EXPENSE_SYSTEM .
/YKY/EXP_COMPID-SYSID =
/YKY/EXP_COMPIDV-SYSID .
/YKY/EXP_COMPID-CLIENT =
/YKY/EXP_COMPIDV-CLIENT .
/YKY/EXP_COMPID-COMPANY_ID =
/YKY/EXP_COMPIDV-COMPANY_ID .
/YKY/EXP_COMPID-USER_ID =
/YKY/EXP_COMPIDV-USER_ID .
    IF SY-SUBRC = 0.
    UPDATE /YKY/EXP_COMPID ##WARN_OK.
    ELSE.
    INSERT /YKY/EXP_COMPID .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/YKY/EXP_COMPIDV-UPD_FLAG,
STATUS_/YKY/EXP_COMPIDV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/YKY/EXP_COMPIDV.
  SELECT SINGLE * FROM /YKY/EXP_COMPID WHERE
EXPENSE_SYSTEM = /YKY/EXP_COMPIDV-EXPENSE_SYSTEM AND
SYSID = /YKY/EXP_COMPIDV-SYSID AND
CLIENT = /YKY/EXP_COMPIDV-CLIENT AND
COMPANY_ID = /YKY/EXP_COMPIDV-COMPANY_ID .
/YKY/EXP_COMPIDV-MANDT =
/YKY/EXP_COMPID-MANDT .
/YKY/EXP_COMPIDV-EXPENSE_SYSTEM =
/YKY/EXP_COMPID-EXPENSE_SYSTEM .
/YKY/EXP_COMPIDV-SYSID =
/YKY/EXP_COMPID-SYSID .
/YKY/EXP_COMPIDV-CLIENT =
/YKY/EXP_COMPID-CLIENT .
/YKY/EXP_COMPIDV-COMPANY_ID =
/YKY/EXP_COMPID-COMPANY_ID .
/YKY/EXP_COMPIDV-USER_ID =
/YKY/EXP_COMPID-USER_ID .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/YKY/EXP_COMPIDV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /YKY/EXP_COMPIDV-EXPENSE_SYSTEM TO
/YKY/EXP_COMPID-EXPENSE_SYSTEM .
MOVE /YKY/EXP_COMPIDV-SYSID TO
/YKY/EXP_COMPID-SYSID .
MOVE /YKY/EXP_COMPIDV-CLIENT TO
/YKY/EXP_COMPID-CLIENT .
MOVE /YKY/EXP_COMPIDV-COMPANY_ID TO
/YKY/EXP_COMPID-COMPANY_ID .
MOVE /YKY/EXP_COMPIDV-MANDT TO
/YKY/EXP_COMPID-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/YKY/EXP_COMPID'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /YKY/EXP_COMPID TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/YKY/EXP_COMPID'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
